-
  name: Test connectivity to target server
  hosts: target1
  tasks: 
       - name: run the service defined in my_project's docker-compose.yml
         shell: docker-compose -f /example-voting-app/docker-compose.yml up 
         register: out
       - debug: var=out.stdout_lines
         
  become: true
