- name: "Get ping response"
  hosts: all
  become: true
  tasks:
   - name: Ensure docker deamon is running
     service:
       name: docker
       state: started
     become: true
     register: result
   - name: docker ps
     shell: docker ps
     register: output
   - debug: 
      - var: result
      - var: output
   
          
         
