- name: "Get ping response"
  hosts: all
  become: true
  tasks:
   - name: Ensure docker deamon is running
     service:
       name: docker
       state: started
     become: true
   - name: check docker status 
     shell: ps aux | grep docker
     register: result
   - debug: 
      var: result
   
          
         
