-
  name: Test connectivity to target server
  hosts: target1
  tasks:
         - name: Deploying the containers
           command: docker-compose up
           args: 
               chdir: /example-voting-app

