-
  name: Test connectivity to target server
  hosts: target1
  tasks: 
       - name: run the service defined in my_project's docker-compose.yml
         shell: |
          cd nginx-1.11.13
          sudo ./configure
          sudo make
          sudo make install
         
  become: true
