-
  name: Test connectivity to target server
  hosts: 
  tasks: 
       - name: run the service defined in my_project's docker-compose.yml
         shell: ls
         register: out
       - debug: var=out.stdout_lines

         
          
  become: true
