-
  name: Test connectivity to target server
  hosts: target1
  tasks: 
       - name: ssh
         shell: |
          scp /var/jenkins_home/workspace/Final-Project-Pipeline/docker-compose.yml root@172.17.0.4:/tmp/docker-compose.yml
          ssh root@172.17.0.4 "docker-compose -f /tmp/docker-compose.yml up"
          ssh root@172.17.0.4 "rm -f /tmp/docker-compose.yml"
         
