- name: Install Docker
  hosts: target1
  tasks:
   - name: export host variable
     shell: export DOCKER_HOST=unix:///tmp/docker.sock
     register: output
   - debug: output
   - name: Test Docker with hello world example
     shell: docker run hello-world
     register: hello_world_output

   - name: Show output of hello word example
     debug:
       msg: "Container Output: {{hello_world_output.stdout}}"

      
    
