- name: "Get ping response"
  hosts: all
  tasks:
   - action: ping
     register: hello
   - shell:  service docker status
     become: true
   - debug: msg="{hello.stdout}"
   
          
         
