-
  name: Test connectivity to target server
  hosts: target1
  tasks: 
       - name: Start docker service
         sysvinit:
          name: docker
          state: started
          enabled: yes
       - name: run the service defined in my_project's docker-compose.yml
         docker_service:
                  project_src: example-voting-app 
  
  become: true
