-
  name: Test connectivity to target server
  hosts: 
  tasks: 
       - name: run the service defined in my_project's docker-compose.yml
         shell: |
          scp -r /var/jenkins_home/workspace/Final-Project-Pipeline root@target1:/newdirectory
          ssh root@target1
          pip install docker-compose
          cd /newdirectory/var/jenkins_home/workspace/Final-Project-Pipeline
          docker-compose up -d
         register: out
       - debug: var=out.stdout_lines

         
  become: true
