-
  name: Test connectivity to target server
  hosts: target1
  tasks:  
         - name: Check the dir
           command: pwd
           
           
         - name: Run the script
           script: /example-voting-app/compose.sh
           
           
 
  become: true
