-
  name: Test connectivity to target server
  hosts: target1
  tasks:          
         - name: Run the script
           command: pwd
           script: /example-voting-app/compose.sh
           
           
 
  become: true
