- name: "Get ping response"
  hosts: all
  become: true
  tasks:
   - name: Ensure docker deamon is running
     service:
       name: docker
       state: started
     become: true
     register: hello
   - debug: msg="{hello.stdout}"
   
          
         
