- name: "Get ping response"
  hosts: all
  tasks:
   - action: ping
     register: hello
   - shell:  |
       service docker status
       service docker start
   - become: true
   - debug: msg="{hello.stdout}"
   
          
         
