-
  name: Test connectivity to target server
  hosts: test
  tasks: 
       - name: ssh
         shell: |
          scp /var/jenkins_home/workspace/Final-Project-Pipeline/docker-compose.yml root@target1:/tmp/docker-compose.yml
          ssh root@target1 "docker-compose -f /tmp/docker-compose.yml up"
          ssh root@target1 "rm -f /tmp/docker-compose.yml"
         
