- name: "Get ping response"
  hosts: all
  become: true
  tasks:
   - action: ping
   - shell: "{{ item }}"
     with_items:
       - service docker status
       - service docker start
       - service docker status
     register: hello
   - debug: msg="{hello.stdout}"
   
          
         
