-
  name: Test connectivity to target server
  hosts: 
  tasks: 
       - name: run the service defined in my_project's docker-compose.yml
       - git:
            repo: https://github.com/DevOps-Pro1/example-voting-app.git
            dest: /example-voting-app
          
  become: true
