-
  name: Test connectivity to target server
  hosts: target1 
  tasks: 
       - name: run the service defined in my_project's docker-compose.yml
         git:
            repo: https://github.com/DevOps-Pro1/example-voting-app.git
            dest: /example-voting-app
       - name: cd
         shell: |
          cd /example-voting-app
          ls -l
          pwd
          service docker status
          service docker restart
          service docker status
          usermod -aG docker ${USER}
          ls -la /var/run/docker.sock
          whereis docker-compose
         register: out
         become: true
       - debug: var=out.stdout_lines
       - name: docker compose
         shell: |
          /usr/bin/docker-compose/docker-compose -f /example-voting-app/docker-compose.yml up
          register: output
         become: true
       - debug: var1=output.stdout_lines
         
