-
  name: Test connectivity to target server
  hosts: target1
  tasks:  
       - name: run the service defined in my_project's docker-compose.yml
         docker_compose:
                  project_src: /example-voting-app/docker-compose.yml          
           
 
  become: true
