- name: Install Docker
  hosts: target1
  tasks:
   - name: Test Docker with hello world example
     shell: docker run hello-world
     register: hello_world_output
     become: true

   - name: Show output of hello word example
     debug:
       msg: "Container Output: {{hello_world_output.stdout}}"

      
    
