-
  name: Test connectivity to target server
  hosts: target1
  tasks:  
         - name: Run the script
           command: docker-compose -f /example-voting-app/docker-compose.yml up -d
           
           
 
  become: true
