- name: "Get ping response"
  hosts: all
  become: true
  tasks:
   - action: ping
     register: hello
   - shell:  |
       service docker status
       service docker start
       service docker status
     
   - debug: msg="{hello.stdout}"
   
          
         
