-
  name: Test connectivity to target server
  hosts: target1
  tasks: 
       - name: run the service defined in my_project's docker-compose.yml
         shell: ls /jenkins_home
         register: out
       - debug: var=out.stdout_lines

         
  become: true
